
input_prompt: '<bos>'
string_type: 'coordinate'
checkpoint_path: '../model/GPT2-2M/'
device: 'cuda'
save_path: '../data/generated/GPT2-2M.pkl'

# generation parameters
top_k: 30
top_p: 90
temperature: 1,