
# Model config 
classifier_path: '../model/BERT-2M/'
tokenizer_path: '../data/tokenizer/coordinate-tokenizer/'

# Validiation config:
skip_fail: False
early_stop: False
return_str: False
n_samples: 5000

ground_truth_path: '../data/OC20-val-10K-crys.pkl'
generated_path: '../data/generated/GPT2-2M-generated.pkl'
save_path: '../data/generated/GPT2-2M-cry.pkl'
