model_params:
    name: '2eORR-fine-tuned-detection-model'
    from_pretrained: './models/oc20-2M-BERT/'
    hidden_size: 512
    num_hidden_layers: 12
    num_attention_heads: 8
    n_epochs: 300
    
data_params:
    tokenizer_path: './data/tokenizer/'
    data_path: './data/corrupted_dataset/2eORR_corrupted/'
    max_len: 1024
    batch_size: 32
    gradient_accumulation_steps: 2
    
  
  
